module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://whatsapp.com/channel/0029Vb8GLHTEgGfI2C0m2Q3N',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.postimg.cc/XJ1kgMY2/8b97d722-c3da-4938-8dae-c9d7a0938968.png',
    NEWSLETTER_JID: '120363348739987203@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ZENIT XND BOT',
    OWNER_NAME: 'TB-ZENIT',
    OWNER_NUMBER: '918945999655',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © 𝒫𝑜𝓌𝑒𝓇𝑒𝒹 𝐵𝓎 𝒜𝓇𝓈𝓁𝒶𝓃𝑀𝒟',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb8GLHTEgGfI2C0m2Q3N',
};
